import Head from "next/head";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";

export default function Home() {
  const { isAuthenticated, user, logout } = useMoralis();

  if (!isAuthenticated) return <Login />;

  return (
    <div className="globalStyle gradientBG">
      <Head>
        <title>Web 3.0 Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h2 className="text-size">Hey There!</h2>
        <p className="userText">
          Your Username is <br /> <span>{user.getUsername()} 🚀</span>
        </p>

        <button onClick={logout} className="btn-2">
          Click to logout
        </button>
      </div>
    </div>
  );
}
